
all: DP_Lopatovsky_Lukas_2017.pdf 

DP_Lopatovsky_Lukas_2017.pdf: DP_Lopatovsky_Lukas_2017.tex
	pdflatex DP_Lopatovsky_Lukas_2017.tex
	pdflatex DP_Lopatovsky_Lukas_2017.tex

clean:
	rm DP_Lopatovsky_Lukas_2017.pdf
	rm DP_Lopatovsky_Lukas_2017.log
	rm DP_Lopatovsky_Lukas_2017.lof
	rm DP_Lopatovsky_Lukas_2017.aux
	rm DP_Lopatovsky_Lukas_2017.out
	rm DP_Lopatovsky_Lukas_2017.toc
